name: Run Linter

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          # version: latest
          # skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout=10m
